# Generated by Django 2.1.5 on 2019-04-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190401_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient',
            name='options',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
