# Generated by Django 2.1.5 on 2019-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190402_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
