# Generated by Django 2.1.5 on 2019-04-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image_image'),
        ('api', '0006_cartitem_sub_total'),
    ]

    operations = [
    ]
