# Generated by Django 2.1.5 on 2019-04-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('C', 'Cart'), ('O', 'Ordered'), ('P', 'Processed'), ('S', 'Shipped')], default='C', max_length=2),
        ),
    ]
