# Generated by Django 2.1.5 on 2019-04-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cartitem_status'),
        ('api', '0007_merge_20190403_0931'),
    ]

    operations = [
    ]
