# Generated by Django 2.1.5 on 2019-04-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190408_1457'),
        ('api', '0012_auto_20190408_0725'),
    ]

    operations = [
    ]
